### ISSUE TITLE
Crash when opening "Settings"

### ISSUE THREAD

**Issue by NevendyND** [Seventhxiv/Collections#1]
Hey i get a Crash when i open the Settings, also the Game closes without crash instant when i type "/co"

[dalamud_appcrash_20230909_120610_440_185032.log](https://github.com/Seventhxiv/Collections/files/12565489/dalamud_appcrash_20230909_120610_440_185032.log)

**Comment by Seventhxiv** [comment]
Couldn't recreate, is it still happening ?

**Comment by KhaosAvagnar** [comment]
for me the settings windown just flash, at first i thought it didn't at a settings at all

**Comment by Seventhxiv** [comment]
> s windown just flash, at first i thought it did

does the command /co open the main window ?
There's no separate settings window

**Comment by KhaosAvagnar** [comment]
the main window open without a problem, just the command /coi is not working

**Comment by Seventhxiv** [comment]
> the main window open without a problem, just the command /coi is not working

That should only work inside an instance.
I'm reworking that window anyway, will also clarify that.

**Comment by KhaosAvagnar** [comment]
ok thank you
