### ISSUE TITLE
Selection Indicator For Content Filters Do Not Update Properly When Moving Window

### ISSUE THREAD

**Issue by SelfAfflicted** [Seventhxiv/Collections#3]
Video will probably be easier to explain

https://github.com/Seventhxiv/Collections/assets/13339406/b1a49144-25ac-41d8-95ff-5e3f7235ca82

What I failed to show is when hovering over the items in the list afterward will update them and appear as intended.

**Comment by Seventhxiv** [comment]
Fixed, will be pushed with next release
