### ISSUE TITLE
[Suggestion] Left-click to select and show items from a single filter, right-click each selected filter to show items from multiple filters together

### ISSUE THREAD

**Issue by SelfAfflicted** [Seventhxiv/Collections#4]
Majority of the time I would prefer to only see items from a single filter at a time, and left-clicking on desired filter was expecting to select it and deselect the previous. Would you consider either moving the current behavior to the right mouse button and adding single selection as described to left? Either this or just adding single selection to right button would be great. I do know I can click the filter a second time to deselect, would be more convenient with less clicks.

**Comment by Seventhxiv** [comment]
I agree the common use is to look at a single filter at any time. I'll consider changing it.

**Comment by Seventhxiv** [comment]
Done, will be pushed with next release
