### ISSUE TITLE
Filter for Unobtained

### ISSUE THREAD

**Issue by jibrilles** [Seventhxiv/Collections#5]
This plugin would be absolutely perfect if we could filter for "Unobtained"!  It's a huge pain to roll over every item to see obtained status as I already have a large collection of mounts and minions. I'd primarily just like to see the ones I still need to get.

**Comment by Seventhxiv** [comment]
Will definitely add this, the filters are pretty basic right now and I'm looking to revamp them

**Comment by Seventhxiv** [comment]
Done, will be added in next release
